Check that localStorage is defined on initial <DarkModeToggle /> render
This fixes an issue where the server raises the following error
> ReferenceError: localStorage is not defined